#!/usr/bin/env bash
# Vendor the front end of anywidget-instruments into assets/.
#
# Usage: scripts/sync-assets.sh [WHEEL_PATH_OR_URL]
#
# The wheel ships everything a host needs (static/index.js, static/index.css,
# static/contract.json, schema/*.schema.json, templates/*.svg); no Python code
# runs. The source map is not vendored, so the sourceMappingURL comment is
# removed from index.js. assets/SOURCE.toml records where the files come from.
set -euo pipefail

DEFAULT_URL="https://s-celles.github.io/anywidget-instruments/marimo/batch_reactor/public/anywidget_instruments-0.1.0.dev0-py3-none-any.whl"
SRC="${1:-$DEFAULT_URL}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/assets"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

if [[ "$SRC" =~ ^https?:// ]]; then
    curl -fsSL -o "$TMP/wheel.whl" "$SRC"
else
    cp "$SRC" "$TMP/wheel.whl"
fi
WHEEL_NAME="$(basename "$SRC")"
SHA256="$(sha256sum "$TMP/wheel.whl" | cut -d' ' -f1)"

(cd "$TMP" && unzip -q wheel.whl 'anywidget_instruments/static/*' 'anywidget_instruments/schema/*' \
    'anywidget_instruments/templates/*' '*.dist-info/licenses/LICENSE')

rm -rf "$DEST"
mkdir -p "$DEST"
PKG="$TMP/anywidget_instruments"
sed '/^\/\/# sourceMappingURL=/d' "$PKG/static/index.js" > "$DEST/index.js"
cp "$PKG/static/index.css" "$PKG/static/contract.json" "$DEST/"
cp -r "$PKG/schema" "$PKG/templates" "$DEST/"
cp "$TMP"/*.dist-info/licenses/LICENSE "$DEST/LICENSE-anywidget-instruments"

VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$DEST/contract.json")"
cat > "$DEST/SOURCE.toml" <<EOF
# Generated by scripts/sync-assets.sh: do not edit.
package = "anywidget-instruments"
version = "$VERSION"
wheel = "$WHEEL_NAME"
sha256 = "$SHA256"
synced = "$(date -u +%Y-%m-%d)"
EOF
echo "Vendored anywidget-instruments $VERSION ($SHA256) into $DEST"
