#!/usr/bin/env bash
# Vendor the front end of anywidget-instruments-industrial into assets/.
#
# Usage: scripts/sync-assets.sh [INDUSTRIAL_WHEEL] [CORE_WHEEL]
#
# Each argument is a path or a URL. The wheel of anywidget-instruments-industrial
# ships everything a host needs (static/index.js, static/index.css,
# static/contract.json, schema/*.schema.json, templates/*.svg); the wheel of the
# anywidget-instruments core adds the base schema the others extend by its $id
# (schema/instrument.schema.json). No Python code runs. The source map is not
# vendored, so the sourceMappingURL comment is removed from index.js.
# assets/SOURCE.toml records where the files come from.
set -euo pipefail

SITE="https://anywidgetinstruments.github.io/anywidget-instruments-industrial/marimo/batch_reactor/public"
SRC="${1:-$SITE/anywidget_instruments_industrial-0.1.0.dev0-py3-none-any.whl}"
CORE_SRC="${2:-$SITE/anywidget_instruments-0.1.0.dev0-py3-none-any.whl}"
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DEST="$ROOT/assets"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

fetch() { # fetch SRC DEST
    if [[ "$1" =~ ^https?:// ]]; then curl -fsSL -o "$2" "$1"; else cp "$1" "$2"; fi
}
sha() { if command -v sha256sum >/dev/null; then sha256sum "$1"; else shasum -a 256 "$1"; fi | cut -d' ' -f1; }

fetch "$SRC" "$TMP/industrial.whl"
fetch "$CORE_SRC" "$TMP/core.whl"
SHA256="$(sha "$TMP/industrial.whl")"
CORE_SHA256="$(sha "$TMP/core.whl")"

# Same wheels as already vendored: keep assets/ as is (no new date, no diff).
if [[ -f "$DEST/SOURCE.toml" ]] && grep -q "^sha256 = \"$SHA256\"" "$DEST/SOURCE.toml" \
    && grep -q "^core_sha256 = \"$CORE_SHA256\"" "$DEST/SOURCE.toml"; then
    echo "assets/ already vendored from these wheels ($SHA256, $CORE_SHA256)"
    exit 0
fi

mkdir -p "$TMP/industrial" "$TMP/core"
(cd "$TMP/industrial" && unzip -q ../industrial.whl 'anywidget_instruments_industrial/static/*' \
    'anywidget_instruments_industrial/schema/*' 'anywidget_instruments_industrial/templates/*' \
    '*.dist-info/licenses/LICENSE')
(cd "$TMP/core" && unzip -q ../core.whl 'anywidget_instruments/schema/*' '*.dist-info/licenses/LICENSE')

rm -rf "$DEST"
mkdir -p "$DEST"
PKG="$TMP/industrial/anywidget_instruments_industrial"
sed '/^\/\/# sourceMappingURL=/d' "$PKG/static/index.js" > "$DEST/index.js"
cp "$PKG/static/index.css" "$PKG/static/contract.json" "$DEST/"
cp -r "$PKG/schema" "$PKG/templates" "$DEST/"
cp "$TMP"/core/anywidget_instruments/schema/*.schema.json "$DEST/schema/"
cp "$TMP"/industrial/*.dist-info/licenses/LICENSE "$DEST/LICENSE-anywidget-instruments-industrial"
cp "$TMP"/core/*.dist-info/licenses/LICENSE "$DEST/LICENSE-anywidget-instruments"

VERSION="$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$DEST/contract.json")"
cat > "$DEST/SOURCE.toml" <<TOML
# Generated by scripts/sync-assets.sh: do not edit.
package = "anywidget-instruments-industrial"
version = "$VERSION"
wheel = "$(basename "$SRC")"
sha256 = "$SHA256"
core_package = "anywidget-instruments"
core_wheel = "$(basename "$CORE_SRC")"
core_sha256 = "$CORE_SHA256"
synced = "$(date -u +%Y-%m-%d)"
TOML
echo "Vendored anywidget-instruments-industrial $VERSION ($SHA256) and the core schema ($CORE_SHA256) into $DEST"
