name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

concurrency:
  group: documentation-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: write
  pull-requests: read
  statuses: write

jobs:
  docs:
    name: Build and deploy the documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: julia-actions/setup-julia@v3
        with:
          version: "1"
      - uses: julia-actions/cache@v3
      - name: Instantiate
        run: julia --color=yes --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --color=yes --project=docs docs/make.jl
